### ISSUE TITLE
None of the example are working

### ISSUE THREAD

**Issue by aboudou** [ameltech/sme-cc2541-library#1]
Hello,

I've tried all of the three examples, but none of them are working. LightBlue BLE scanner can't detect the board (the scanner is working, it can detect another BLE board, the not the SmartEverything one). I've tried to reverse plug the TDK module as there are no indication on how it should be plugged, but nothing is working.

Regards

**Comment by searobin** [comment]
Hi Arnaud.

It could be that the FW present on your SmartEverything is not the one is needed for this library

In order to known if this is the case, please send an email to 
*development@axelelettronica.it \* with the:
S/N,  ID and PAC.

Together with your shipping address and we will proceed with the substitution of the BLE chip is in your hand if it comes from the wrong stock.

In order to speed up our internal steps, please use the following subject :
"replace of TDK BLE of SmartEverything FOX"
