### ISSUE TITLE
sketch\cc2541.cpp:9:19: fatal error: Uart.h: No such file or directory

### ISSUE THREAD

**Issue by ragflyer** [ameltech/sme-cc2541-library#2]
After removing all the SerialUSB code which produced errors on a standard Arduino IDE environment, I still receive the above error and cannot find any lib containing the Uart.h file.
Any hints on how to solve this?

**Comment by smkkHw** [comment]
ciao @ragflyer:

In order to address better your request I should ask U some small questions (eve if looks like stupid question).
1) Did U download the 2 core from the board manager GenuinoZero & SmartEverything ?(the second for sure
2) Did U select the SmartEverything from the Board menu?

Because the issue U are facing is not visible with the IDE I'm using (1.6.9)
`
...
"C:\Users\smkkHw\AppData\Local\Arduino15\packages\arduino\tools\arm-none-eabi-gcc\4.8.3-2014q1/bin/arm-none-eabi-g++" -mcpu=cortex-m0plus -mthumb -c -g -Os -w -std=gnu++11 -ffunction-sections -fdata-sections -fno-threadsafe-statics -nostdlib --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -MMD -DF_CPU=48000000L -DARDUINO=10609 -DARDUINO_SAMD_SMARTEVERYTHING -DARDUINO_ARCH_SAMD  -D__SAMD21J18A__ -DUSB_VID=0x2341 -DUSB_PID=0xe002 -DUSBCON '-DUSB_MANUFACTURER="Amel-Tech"' '-DUSB_PRODUCT="Smart Everything Fox"' "-IC:\Users\smkkHw\AppData\Local\Arduino15\packages\arduino\tools\CMSIS\4.0.0-atmel/CMSIS/Include/" "-IC:\Users\smkkHw\AppData\Local\Arduino15\packages\arduino\tools\CMSIS\4.0.0-atmel/Device/ATMEL/" "-IC:\Users\smkkHw\AppData\Local\Arduino15\packages\arduino\hardware\samd\1.6.6\cores\arduino" "-IC:\Users\smkkHw\AppData\Local\Arduino15\packages\AMEL\hardware\samd\1.1.0\variants\AMEL_SmartEverything" "C:\Users\smkkHw\AppData\Local\Arduino15\packages\arduino\hardware\samd\1.6.6\cores\arduino\Uart.cpp" -o "C:\Users\smkkHw\AppData\Local\Temp\build1f599afb27e7d72705fa00601c19a6d4.tmp\core\Uart.cpp.o"

...

"C:\Users\smkkHw\AppData\Local\Arduino15\packages\arduino\tools\arm-none-eabi-gcc\4.8.3-2014q1/bin/arm-none-eabi-gcc"  "-LC:\Users\smkkHw\AppData\Local\Temp\build1f599afb27e7d72705fa00601c19a6d4.tmp" -Os -Wl,--gc-sections -save-temps  "-TC:\Users\smkkHw\AppData\Local\Arduino15\packages\AMEL\hardware\samd\1.1.0\variants\AMEL_SmartEverything/linker_scripts/gcc/flash_with_bootloader.ld" "-Wl,-Map,C:\Users\smkkHw\AppData\Local\Temp\build1f599afb27e7d72705fa00601c19a6d4.tmp/SerialCommunication.ino.map" --specs=nano.specs --specs=nosys.specs -mcpu=cortex-m0plus -mthumb -Wl,--cref -Wl,--check-sections -Wl,--gc-sections -Wl,--unresolved-symbols=report-all -Wl,--warn-common -Wl,--warn-section-align -o "C:\Users\smkkHw\AppData\Local\Temp\build1f599afb27e7d72705fa00601c19a6d4.tmp/SerialCommunication.ino.elf" "C:\Users\smkkHw\AppData\Local\Temp\build1f599afb27e7d72705fa00601c19a6d4.tmp\sketch\SerialCommunication.ino.cpp.o" "C:\Users\smkkHw\AppData\Local\Temp\build1f599afb27e7d72705fa00601c19a6d4.tmp\libraries\SmartEverything_CC2541\ble\cc2541.cpp.o" "C:\Users\smkkHw\AppData\Local\Temp\build1f599afb27e7d72705fa00601c19a6d4.tmp\core\WireIoExt.cpp.o" "C:\Users\smkkHw\AppData\Local\Temp\build1f599afb27e7d72705fa00601c19a6d4.tmp\core\internalI2C.cpp.o" "C:\Users\smkkHw\AppData\Local\Temp\build1f599afb27e7d72705fa00601c19a6d4.tmp\core\variant.cpp.o" "C:\Users\smkkHw\AppData\Local\Temp\build1f599afb27e7d72705fa00601c19a6d4.tmp\core\variantInit.cpp.o" -Wl,--start-group -lm "C:\Users\smkkHw\AppData\Local\Temp\build1f599afb27e7d72705fa00601c19a6d4.tmp/core\core.a" -Wl,--end-group
"C:\Users\smkkHw\AppData\Local\Arduino15\packages\arduino\tools\arm-none-eabi-gcc\4.8.3-2014q1/bin/arm-none-eabi-objcopy" -O binary  "C:\Users\smkkHw\AppData\Local\Temp\build1f599afb27e7d72705fa00601c19a6d4.tmp/SerialCommunication.ino.elf" "C:\Users\smkkHw\AppData\Local\Temp\build1f599afb27e7d72705fa00601c19a6d4.tmp/SerialCommunication.ino.bin"
Using library SmartEverything_CC2541 at version 1.0.1 in folder: C:\Users\smkkHw\Documents\Arduino\libraries\SmartEverything_CC2541 

Sketch uses 11,816 bytes (4%) of program storage space. Maximum is 262,144 bytes.
`

**Comment by searobin** [comment]
SerialUSB should not generate errors.

I would remove and reinstall GenuinoZero & SmartEverything 
from scratch.

Maybe Arduino as well.

**Comment by jihadfee** [comment]
I just got a cc2541 BLE and got the same error "Uart.h: No such file or directory"
what I found is this
I have is a 
Arduino Genuino Mega 2560
BLE cc2541
Arduino 1.8.0
SmartEverything CC2541 which it get's install in my local library (BLEBridge in NOT in the LIST)

when Compiling I get this error

/Users/xxxxx/Documents/Arduino/libraries/SmartEverything_CC2541/src/ble/cc2541.cpp:9:19: fatal error: Uart.h: No such file or directory
  #include <Uart.h>

looking in to the problem I found this

it Does not exist in this directory

/Users/jihad/Library/Arduino15/packages/arduino/hardware/avr/1.6.17/cores/arduino

but it does in 

/Users/jihad/Library/Arduino15/packages/arduino/hardware/samd/1.6.11/cores/arduino

so the cc2541 Library Does not work on an AVR "Ateml" but only on a  "samd" system because of the uart library.


please can fix this, it will be appreciated to work on a AVR Board. 

Thanks

**Comment by searobin** [comment]
I'm sorry. We do not have effort to work on this issue. Please, feel free to fork the library and change it by yourself, for your needings.
